# Generated by Django 2.2.5 on 2019-09-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_auto_20190918_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='subTime',
            field=models.CharField(default='', max_length=15),
        ),
    ]
